INSERT INTO roles (NAMEROLE, DESCRIPTIONROLE, STATEDELETE) VALUES ('Administrador','Administrador del sistema',0);

INSERT INTO users (USERNAME, FIRSTNAME, LASTNAME, IDENTITYDOCUMENT, AGE, PHONENUMBER, EMAIL, IDROL, STATEDELETE, PASSWORD)
VALUES ('ericka','Ericka','Montero','20593044',26,'3053486939','ericka@gmail.com',1,0,'123456');