-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 00:07:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema srb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema srb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `srb` DEFAULT CHARACTER SET utf8 ;
USE `srb` ;

-- -----------------------------------------------------
-- Table `srb`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `srb`.`vehicle` (
  `idVEHICLE` INT(11) NOT NULL,
  `MARK` VARCHAR(45) NULL DEFAULT NULL,
  `LICENSEPLATE` VARCHAR(45) NULL DEFAULT NULL,
  `YEAR` INT NULL DEFAULT NULL,
  `TON` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idVEHICLE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena la informacion de los vehiculos';


-- -----------------------------------------------------
-- Table `srb`.`assignedvehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`assignedvehicle` ;

CREATE TABLE IF NOT EXISTS `srb`.`assignedvehicle` (
  `idASSIGNEDVEHICLE` INT(11) NOT NULL,
  `IDDRIVER` INT(11) NULL DEFAULT NULL,
  `IDVEHICLE` INT(11) NULL DEFAULT NULL,
  `DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idASSIGNEDVEHICLE`),
  INDEX `VEHICLEFK_idx` (`IDVEHICLE` ASC),
  CONSTRAINT `VEHICLEFK`
    FOREIGN KEY (`IDVEHICLE`)
    REFERENCES `srb`.`vehicle` (`idVEHICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena la informacion de los vehiculos asignados\n';


-- -----------------------------------------------------
-- Table `srb`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`device` ;

CREATE TABLE IF NOT EXISTS `srb`.`device` (
  `idDEVICE` INT(11) NOT NULL,
  `MARK` VARCHAR(150) NULL DEFAULT NULL,
  `MODEL` VARCHAR(150) NULL DEFAULT NULL,
  `IMEI` VARCHAR(100) NULL DEFAULT NULL,
  `PHONENUMBER` VARCHAR(45) NULL DEFAULT NULL,
  `IDDRIVER` INT(11) NULL DEFAULT NULL,
  `users_idusers` INT NOT NULL,
  `users_roles_idroles` INT NOT NULL,
  `vehicle_idVEHICLE` INT(11) NOT NULL,
  PRIMARY KEY (`idDEVICE`, `users_idusers`, `users_roles_idroles`, `vehicle_idVEHICLE`),
  INDEX `fk_device_vehicle1_idx` (`vehicle_idVEHICLE` ASC),
  CONSTRAINT `fk_device_vehicle1`
    FOREIGN KEY (`vehicle_idVEHICLE`)
    REFERENCES `srb`.`vehicle` (`idVEHICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena la informacion de los dispositivos';


-- -----------------------------------------------------
-- Table `srb`.`routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`routes` ;

CREATE TABLE IF NOT EXISTS `srb`.`routes` (
  `idROUTES` INT(11) NOT NULL,
  `NAMEROUTES` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(400) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `device_idDEVICE` INT(11) NOT NULL,
  `device_users_idusers` INT NOT NULL,
  `device_users_roles_idroles` INT NOT NULL,
  PRIMARY KEY (`idROUTES`, `device_idDEVICE`, `device_users_idusers`, `device_users_roles_idroles`),
  INDEX `fk_routes_device1_idx` (`device_idDEVICE` ASC, `device_users_idusers` ASC, `device_users_roles_idroles` ASC),
  CONSTRAINT `fk_routes_device1`
    FOREIGN KEY (`device_idDEVICE` , `device_users_idusers` , `device_users_roles_idroles`)
    REFERENCES `srb`.`device` (`idDEVICE` , `users_idusers` , `users_roles_idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'Tabla que almacena las rutas';


-- -----------------------------------------------------
-- Table `srb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`location` ;

CREATE TABLE IF NOT EXISTS `srb`.`location` (
  `idLOCATION` INT(11) NOT NULL,
  `IDVEHICLE` INT(11) NULL DEFAULT NULL,
  `LOCATIONLATITUDE` VARCHAR(100) NULL DEFAULT NULL,
  `LOCATIONLENGTH` VARCHAR(100) NULL DEFAULT NULL,
  `DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idLOCATION`),
  INDEX `FKVEHICLE_idx` (`IDVEHICLE` ASC),
  CONSTRAINT `FKVEHICLE`
    FOREIGN KEY (`IDVEHICLE`)
    REFERENCES `srb`.`vehicle` (`idVEHICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena la informacion de la ubicacion del vehiculo';


-- -----------------------------------------------------
-- Table `srb`.`routedetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`routedetail` ;

CREATE TABLE IF NOT EXISTS `srb`.`routedetail` (
  `idROUTEDETAIL` INT(11) NOT NULL,
  `IDROUTE` INT(11) NULL DEFAULT NULL,
  `ROUTELATITUDE` VARCHAR(200) NULL DEFAULT NULL,
  `ROUTELENGTH` VARCHAR(200) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idROUTEDETAIL`),
  INDEX `ROUTEFK_idx` (`IDROUTE` ASC),
  CONSTRAINT `ROUTEFK`
    FOREIGN KEY (`IDROUTE`)
    REFERENCES `srb`.`routes` (`idROUTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci
COMMENT = 'Tabla que almacena la informacion del detalle de la ruta';


-- -----------------------------------------------------
-- Table `srb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`roles` ;

CREATE TABLE IF NOT EXISTS `srb`.`roles` (
  `idroles` INT NOT NULL,
  `role` VARCHAR(45) NULL,
  `DescriptionRole` VARCHAR(400) NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`users` ;

CREATE TABLE IF NOT EXISTS `srb`.`users` (
  `idusers` INT NOT NULL,
  `userName` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  `firstName` VARCHAR(100) NULL,
  `LastName` VARCHAR(45) NULL,
  `IdentityDocument` VARCHAR(45) NULL,
  `age` INT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `Email` VARCHAR(200) NULL,
  `roles_idroles` INT NOT NULL,
  `assignedvehicle_idASSIGNEDVEHICLE` INT(11) NOT NULL,
  PRIMARY KEY (`idusers`, `roles_idroles`, `assignedvehicle_idASSIGNEDVEHICLE`),
  INDEX `fk_users_roles1_idx` (`roles_idroles` ASC),
  INDEX `fk_users_assignedvehicle1_idx` (`assignedvehicle_idASSIGNEDVEHICLE` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `srb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_assignedvehicle1`
    FOREIGN KEY (`assignedvehicle_idASSIGNEDVEHICLE`)
    REFERENCES `srb`.`assignedvehicle` (`idASSIGNEDVEHICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srb`.`Audits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srb`.`Audits` ;

CREATE TABLE IF NOT EXISTS `srb`.`Audits` (
  `idAudits` INT NOT NULL,
  `Operation` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `statusOperation` INT NULL,
  `conten` VARCHAR(3000) NULL,
  `users_idusers` INT NOT NULL,
  `users_roles_idroles` INT NOT NULL,
  `users_assignedvehicle_idASSIGNEDVEHICLE` INT(11) NOT NULL,
  PRIMARY KEY (`idAudits`, `users_idusers`, `users_roles_idroles`, `users_assignedvehicle_idASSIGNEDVEHICLE`),
  INDEX `fk_Audits_users1_idx` (`users_idusers` ASC, `users_roles_idroles` ASC, `users_assignedvehicle_idASSIGNEDVEHICLE` ASC),
  CONSTRAINT `fk_Audits_users1`
    FOREIGN KEY (`users_idusers` , `users_roles_idroles` , `users_assignedvehicle_idASSIGNEDVEHICLE`)
    REFERENCES `srb`.`users` (`idusers` , `roles_idroles` , `assignedvehicle_idASSIGNEDVEHICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
